# Generated by Django 3.2.7 on 2021-09-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_pro_lang_tag_level_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dev',
            name='lang',
            field=models.ManyToManyField(to='home.Taglag'),
        ),
        migrations.AddField(
            model_name='dev',
            name='other_lang',
            field=models.CharField(default='new', max_length=50),
        ),
    ]
