# Generated by Django 3.2.7 on 2021-09-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210920_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='dev',
            name='job',
            field=models.ManyToManyField(default='fulltime', to='home.Tagjob'),
        ),
    ]
