# Generated by Django 3.2.7 on 2021-09-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_dev_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev',
            name='job',
            field=models.ManyToManyField(default='Fulltime', to='home.Tagjob'),
        ),
    ]
