# Generated by Django 3.2.7 on 2021-09-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_dev_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev',
            name='Describe_yourself',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dev',
            name='level',
            field=models.ManyToManyField(default='midlevel', to='home.Tag_level'),
        ),
    ]
