# Generated by Django 3.2.7 on 2021-09-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210922_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev',
            name='level',
            field=models.ManyToManyField(to='home.Tag_level'),
        ),
    ]
